# Generated by Django 3.2.3 on 2021-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tech', models.TextField(default='not specified', max_length=5000)),
                ('about', models.TextField(max_length=10000)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
