# Generated by Django 3.2.3 on 2021-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='about',
            field=models.TextField(max_length=5000),
        ),
    ]
